export type Vehicle = {
  uniqueCode: string;
  modelCode: string;
  brand: string;
  model: string;
  year: number;
  modelYear: number;
  color: string;
  price: number;
  purchasePrice: number;
  purchaseDate: string;
  availability: boolean;
  quantity: number;
  odometer: number;
  description: string;
  segment: string;
  options: string[];
  licensePlate: string;
  chassis: string;
};
